server
{
	server_name first;
	listen 127.0.0.1:8080;

	root /www;
	client_max_body_size 5M;
	autoindex on;

	location /
	{
		root /www;
		allowed_methods GET;
		autoindex on;
		index /index.html;
	}
}

server
{
	server_name second;
	listen 127.0.0.1:8081;

	root /www;
	client_max_body_size 5M;
	autoindex on;

	location /
	{
		root /www;
		allowed_methods GET;
		autoindex on;
		index /index.html;
	}
}

