server
{
	server_name test;
	listen 127.0.0.1:8080;

	root /www;
	client_max_body_size 5M;
	autoindex on;

	location /
	{
		root /www;
		allowed_methods GET;
		index /index.html;
	}
}

server
{
	server_name test;
	listen 127.0.0.2:8080;

	root /www;
	client_max_body_size 5M;
	autoindex on;

	location /
	{
		root /www;
		allowed_methods GET;
		index /index.html;
	}
}

server
{
	server_name test;
	listen 127.0.0.3:8080;

	root /www;
	client_max_body_size 5M;
	autoindex on;

	location /
	{
		root /www;
		allowed_methods GET;
		index /index.html;
	}
}