server
{
    server_name location_test;

    listen 127.0.0.1:8082;

    root /www;

    client_max_body_size 5M;

    autoindex on;

    error_page 404 /www/error_pages/non-default/404.html;

    location /
    {
        root /www;
        allowed_methods GET;
        autoindex on;
        index /index.html;
    }

    location /location_a
    {
        root /www;
        allowed_methods GET;
        autoindex on;
    }

    location /location_b
    {
        root /random;
        allowed_methods GET;
        autoindex on;
    }
}