server {
	server_name	example.org www.example.org;
	listen 112.111.112.0:8080;
	root /data;
	client_max_body_size 5M;
	cgi_pass .py /usr/bin/python3;
	autoindex on;

	error_page 400 /error_pages/400.html;
	error_page 403 /error_pages/403.html;
	error_page 404 /error_pages/404.html;
	error_page 405 /error_pages/405.html;
	error_page 413 /error_pages/413.html;
	error_page 500 /error_pages/500.html;
	error_page 502 /error_pages/502.html;

	location /concerts {
		index /html/index.html;
		allowed_methods GET POST DELETE;
		upload_store /upload;
		cgi_pass .py /usr/bin/python3;
		autoindex off;
		return 303 https://google.com;
	}

	location / {
		root /data;
		index /html/index.html;
		allowed_methods GET POST;
		upload_store /upload;	
		autoindex on;

    	}

# 	# CGI Handler
	location /cgi-bin {
		root /data/cgi-bin;
		cgi_pass .py /usr/bin/python3;
		allowed_methods GET POST DELETE;
		autoindex off;
	}

	location /images {
		root  /data/images;
		index  index.html;
		allowed_methods  GET;
		autoindex off;
	}

	location /upload {
		root  /data/upload;
		index index.html;
		allowed_methods  GET POST DELETE;
		autoindex off;
	}

}

#server {
#	listen 127.0.0.1:8082;
#	client_max_body_size  50000;
#
#    location / {
#		root  /data/web2;
#		index  index.html .html;
#		allowed_methods  GET POST DELETE;
#		autoindex  off;
#	}
#}
