server 
{
	server_name webserv;
	listen 127.0.0.1:8080;
	root /www;
	client_max_body_size 5M;
	autoindex on;
	
	error_page 404 /error_pages/non-default/404.html;
	
	location /testing_return
	{
		root /folder_01;
		return 300 /error_pages/300.html;
		allowed_methods GET POST;
		autoindex on;
	}

	location /
	{
		root /www;
		allowed_methods GET POST DELETE;
		upload_store /upload;
		cgi_pass .py /confetti.py;
		autoindex on;
		index /index.html;
	}

	location /upload
	{
		root /www;
		allowed_methods GET;
		autoindex on;
	}
	location /redirect {
		allowed_methods GET;
		return 302 /redirected.html;
		index /index.html;
	}
}
