server 
{
	server_name webserv;
	listen 127.0.0.1:8080;
	root /www;
	client_max_body_size 5M;
	autoindex on;
	
	error_page 404 /www/error_pages/non-default/404.html;
	
	location /testing_return
	{
		return 302 /error_pages/300.html;
		allowed_methods GET POST;
		autoindex on;
	}

	location /
	{
		root /www;
		allowed_methods GET POST DELETE;
		upload_store /upload;
		cgi_pass .py /confetti.py;
		autoindex on;
		client_max_body_size 3M;
		index /index.html;
	}

	location /upload
	{
		root /www;
		allowed_methods GET DELETE;
		autoindex on;
		client_max_body_size 3M;
	}

	location /redirect {
		allowed_methods GET;
		return 302 /redirected.html;
		index /index.html;
	}
	
	location /timeout_script
	{
		root /www;
		allowed_methods GET;
		autoindex on;
		cgi_pass .py /timeout_test.py;
	}
	location /imgs 
	{
		root /www;
		allowed_methods GET;
		autoindex on;
	}
	location /fake 
	{
		root /www;
		allowed_methods GET;
		autoindex on;
		cgi_pass .py /timeout_test.py;
	}
	location /cgi_test
	{
		root /www;
		allowed_methods GET POST;
		autoindex on;
		cgi_pass .py /cgi_test.py;
	}
	location /query_test
	{
		root /www;
		allowed_methods GET POST;
		autoindex off;
		cgi_pass .py /query_test.py;
	}
}
