server 
{
	server_name webserv;
	listen 127.0.0.1:8080;
	# root /home/aalombro/projects/webserv/www;
	root /www;
	client_max_body_size 5M;
	autoindex on;
	
	# error_page 300 /home/aalombro/projects/webserv/error_pages/300.html;
	error_page 400 /error_pages/400.html;
	error_page 401 /error_pages/401.html;
	error_page 404 /error_pages/404.html;
	
	location /testing_return
	{
		root /folder_01;
		return 300 /error_pages/300.html;
		allowed_methods GET POST;
		autoindex on;
	}

	location /
	{
		root /www;
		allowed_methods GET POST DELETE;
		upload_store /upload;
		cgi_pass .py /confetti.py;
		autoindex on;
	}
}
