server {
	server_name test42;
	listen 8080;
	root /YoupiBanane;
	client_max_body_size 100;

	location / {
		allowed_methods GET;
		autoindex on;
	}

	location /directory {
		allowed_methods GET;
		root /YoupiBanane;
		autoindex on;
		cgi_pass .bad_extension /youpi.bad_extension;
	}
 
	location /post_body {
		autoindex on;
		allowed_methods POST;
		root /YoupiBanane;
	}
}
