server {
	server_name test42;
	listen 8888;
	root /YoupiBanane;

	location / {
		allowed_methods GET;
		index /index.html;
		cgi_pass .bla cgi_tester;
	}

	location /directory {
		allowed_methods GET;
		root /YoupiBanane;
		index /youpi.bad_extension;
		cgi_pass .bla cgi_tester;
	}
 
	location /post_body {
		allowed_methods POST;
		root /YoupiBanane;
		client_max_body_size 100;
		cgi_pass .bla cgi_tester;
	}
}